"""Initial migration - create user and sweet tables

Revision ID: d944506f6613
Revises: 
Create Date: 2025-09-19 13:09:11.197529+00:00

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd944506f6613'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
